name: sergeev2020a
channels:
- conda-forge
- dennissergeev
dependencies:
- aeolus>=0.4.3
- cartopy
- dask
- ipykernel
- iris>=2.3
- jupyter
- matplotlib
- metpy
- mo_pack
- netCDF4
- numpy
- pandas
- python>=3.7
- pip
- pytest
- python-stratify
- pyvista
- scipy
- tqdm
- xarray
- pip:
  - fastprogress
  - latlon23
  - loguru
